name: Build R4S
on:
  workflow_dispatch:
    inputs:
      debug:
        type: choice
        description: 'debug?'
        options:
        - true
        - false
        default: 'false'
        required: true
      package_clean:
        type: choice
        description: 'check to make clean package'
        options:
        - true
        - false
        default: 'true'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger R4S Build
          run: |
            curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.SEC_TOKEN }}" \
            -d '{"event_type": "r4s", "client_payload": {"branch": "main", "device": "r4s"}}'
